apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: {{ .Values.name }}
spec:
  accessModes:
    - {{ .Values.accessMode | quote }}
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.size | quote }}
